FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install uvicorn

COPY dnd_character_creator ./dnd_character_creator
COPY scraped_data ./scraped_data

CMD ["uv", "run", "uvicorn", "dnd_character_creator.server.app:app", "--host", "0.0.0.0", "--port", "8000"]
