from __future__ import annotations

from enum import StrEnum

from dnd_character_creator.character.race.race import Race
from frozendict import frozendict


class Subrace(StrEnum):
    """Enumeration of all available D&D 5e subraces with sources."""

    AARAKOCRA_AARAKOCRA_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Aarakocra (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    AASIMAR_FALLEN_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Fallen Aasimar (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    AASIMAR_PROTECTOR_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Protector Aasimar (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    AASIMAR_SCOURGE_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Scourge Aasimar (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    AASIMAR_FALLEN_AASIMAR_VOLOSGUIDETOMONSTERS = (
        "Fallen Aasimar (VolosGuidetoMonsters)"
    )
    AASIMAR_PROTECTOR_AASIMAR_VOLOSGUIDETOMONSTERS = (
        "Protector Aasimar (VolosGuidetoMonsters)"
    )
    AASIMAR_SCOURGE_AASIMAR_VOLOSGUIDETOMONSTERS = (
        "Scourge Aasimar (VolosGuidetoMonsters)"
    )
    BUGBEAR_BUGBEAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Bugbear (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    BUGBEAR_BUGBEAR_VOLOSGUIDETOMONSTERS = "Bugbear (VolosGuidetoMonsters)"
    CENTAUR_GRUUL_CENTAUR_GUILDMASTERSGUIDETORAVNICA = (
        "Gruul Centaur (GuildmastersGuidetoRavnica)"
    )
    CENTAUR_SELESNYA_CENTAUR_GUILDMASTERSGUIDETORAVNICA = (
        "Selesnya Centaur (GuildmastersGuidetoRavnica)"
    )
    CENTAUR_CENTAURS_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Centaurs (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    CENTAUR_LAGONNA_MYTHICODYSSEYSOFTHEROS = "Lagonna (MythicOdysseysofTheros)"
    CENTAUR_PHERES_MYTHICODYSSEYSOFTHEROS = "Pheres (MythicOdysseysofTheros)"
    CHANGELING_CHANGELING_EBERRONRISINGFROMTHELASTWAR = (
        "Changeling (EberronRisingfromtheLastWar)"
    )
    CHANGELING_CHANGELING_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Changeling (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    CHANGELING_CHANGELING_UNEARTHEDARCANA = "Changeling (UnearthedArcana)"
    DRAGONBORN_DRACONBLOOD_EXPLORERSGUIDETOWILDEMOUNT = (
        "Draconblood (ExplorersGuidetoWildemount)"
    )
    DRAGONBORN_RAVENITE_EXPLORERSGUIDETOWILDEMOUNT = (
        "Ravenite (ExplorersGuidetoWildemount)"
    )
    DRAGONBORN_CHROMATIC_FIZBANSTREASURYOFDRAGONS = (
        "Chromatic (FizbansTreasuryofDragons)"
    )
    DRAGONBORN_GEM_FIZBANSTREASURYOFDRAGONS = "Gem (FizbansTreasuryofDragons)"
    DRAGONBORN_METALLIC_FIZBANSTREASURYOFDRAGONS = (
        "Metallic (FizbansTreasuryofDragons)"
    )
    DRAGONBORN_DRAGONBORN_PLAYERSHANDBOOK = "Dragonborn (PlayersHandbook)"
    DRAGONBORN_CHROMATIC_UNEARTHEDARCANA = "Chromatic (UnearthedArcana)"
    DRAGONBORN_GEM_UNEARTHEDARCANA = "Gem (UnearthedArcana)"
    DRAGONBORN_METALLIC_UNEARTHEDARCANA = "Metallic (UnearthedArcana)"
    DWARF_HILL_DWARF_PLAYERSHANDBOOK = "Hill Dwarf (PlayersHandbook)"
    DWARF_MOUNTAIN_DWARF_PLAYERSHANDBOOK = "Mountain Dwarf (PlayersHandbook)"
    ELF_MARK_OF_SHADOW_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Shadow (EberronRisingfromtheLastWar)"
    )
    ELF_PALLID_ELF_EXPLORERSGUIDETOWILDEMOUNT = (
        "Pallid Elf (ExplorersGuidetoWildemount)"
    )
    ELF_BISHTAHAR_ELF_PLANESHIFTKALADESH = "Bishtahar Elf (PlaneShiftKaladesh)"
    ELF_TIRAHAR_ELF_PLANESHIFTKALADESH = "Tirahar Elf (PlaneShiftKaladesh)"
    ELF_VAHADAR_ELF_PLANESHIFTKALADESH = "Vahadar Elf (PlaneShiftKaladesh)"
    ELF_JURAGA_PLANESHIFTZENDIKAR = "Juraga (PlaneShiftZendikar)"
    ELF_MUL_DAYA_PLANESHIFTZENDIKAR = "Mul Daya (PlaneShiftZendikar)"
    ELF_TAJURU_PLANESHIFTZENDIKAR = "Tajuru (PlaneShiftZendikar)"
    ELF_DARK_ELF_PLAYERSHANDBOOK = "Dark Elf (PlayersHandbook)"
    ELF_HIGH_ELF_PLAYERSHANDBOOK = "High Elf (PlayersHandbook)"
    ELF_WOOD_ELF_PLAYERSHANDBOOK = "Wood Elf (PlayersHandbook)"
    ELF_ASTRAL_ELF_SPELLJAMMERADVENTURESINSPACE = (
        "Astral Elf (SpelljammerAdventuresinSpace)"
    )
    FIRBOLG_FIRBOLG_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Firbolg (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    FIRBOLG_FIRBOLG_VOLOSGUIDETOMONSTERS = "Firbolg (VolosGuidetoMonsters)"
    GENASI_AIR_AIR_GENASI_ELEMENTALEVILPLAYERSCOMPANION = (
        "Air Genasi (ElementalEvilPlayersCompanion)"
    )
    GENASI_AIR_AIR_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Air Genasi (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GENASI_EARTH_EARTH_GENASI_ELEMENTALEVILPLAYERSCOMPANION = (
        "Earth Genasi (ElementalEvilPlayersCompanion)"
    )
    GENASI_EARTH_EARTH_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Earth Genasi (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GENASI_FIRE_FIRE_GENASI_ELEMENTALEVILPLAYERSCOMPANION = (
        "Fire Genasi (ElementalEvilPlayersCompanion)"
    )
    GENASI_FIRE_FIRE_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Fire Genasi (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GENASI_WATER_WATER_GENASI_ELEMENTALEVILPLAYERSCOMPANION = (
        "Water Genasi (ElementalEvilPlayersCompanion)"
    )
    GENASI_WATER_WATER_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Water Genasi (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GNOME_MARK_OF_SCRIBING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Scribing (EberronRisingfromtheLastWar)"
    )
    GNOME_FOREST_GNOME_PLAYERSHANDBOOK = "Forest Gnome (PlayersHandbook)"
    GNOME_ROCK_GNOME_PLAYERSHANDBOOK = "Rock Gnome (PlayersHandbook)"
    GOBLIN_DANKWOOD_GOBLIN_ADVENTURESWITHMUKDANKWOOD = (
        "Dankwood Goblin (AdventureswithMukDankwood)"
    )
    GOBLIN_GOBLIN_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Goblin (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GOBLIN_GOBLIN_PLANESHIFTIXALAN = "Goblin (PlaneShiftIxalan)"
    GOBLIN_GOBLIN_VOLOSGUIDETOMONSTERS = "Goblin (VolosGuidetoMonsters)"
    GOLIATH_GOLIATH_ELEMENTALEVILPLAYERSGUIDE = (
        "Goliath (ElementalEvilPlayersGuide)"
    )
    GOLIATH_GOLIATH_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Goliath (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    GRUNG_GRUNG_PLAYERSHANDBOOK = "Grung (PlayersHandbook)"
    HALF_ELF_AQUATIC_ELF_HERITAGE_PLAYERSHANDBOOK = (
        "Aquatic Elf Heritage (PlayersHandbook)"
    )
    HALF_ELF_DARK_ELF_HERITAGE_PLAYERSHANDBOOK = (
        "Dark Elf Heritage (PlayersHandbook)"
    )
    HALF_ELF_HIGH_ELF_HERITAGE_PLAYERSHANDBOOK = (
        "High Elf Heritage (PlayersHandbook)"
    )
    HALF_ELF_WOOD_ELF_HERITAGE_PLAYERSHANDBOOK = (
        "Wood Elf Heritage (PlayersHandbook)"
    )
    HALF_ORC_MARK_OF_FINDING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Finding (EberronRisingfromtheLastWar)"
    )
    HALF_ORC_HALF_ORC_PLAYERSHANDBOOK = "Half-Orc (PlayersHandbook)"
    HALFLING_MARK_OF_HEALING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Healing (EberronRisingfromtheLastWar)"
    )
    HALFLING_MARK_OF_HOSPITALITY_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Hospitality (EberronRisingfromtheLastWar)"
    )
    HALFLING_LOTUSDEN_HALFLING_EXPLORERSGUIDETOWILDEMOUNT = (
        "Lotusden Halfling (ExplorersGuidetoWildemount)"
    )
    HALFLING_LIGHTFOOT_PLAYERSHANDBOOK = "Lightfoot (PlayersHandbook)"
    HALFLING_STOUT_PLAYERSHANDBOOK = "Stout (PlayersHandbook)"
    HALFLING_GHOSTWISE_SWORDCOASTADVENTURERSGUIDE = (
        "Ghostwise (SwordCoastAdventurersGuide)"
    )
    HOBGOBLIN_HOBGOBLIN_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Hobgoblin (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    HOBGOBLIN_HOBGOBLIN_UNEARTHEDARCANA = "Hobgoblin (UnearthedArcana)"
    HOBGOBLIN_HOBGOBLIN_VOLOSGUIDETOMONSTERS = (
        "Hobgoblin (VolosGuidetoMonsters)"
    )
    HUMAN_MARK_OF_FINDING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Finding (EberronRisingfromtheLastWar)"
    )
    HUMAN_MARK_OF_HANDLING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Handling (EberronRisingfromtheLastWar)"
    )
    HUMAN_MARK_OF_MAKING_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Making (EberronRisingfromtheLastWar)"
    )
    HUMAN_MARK_OF_PASSAGE_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Passage (EberronRisingfromtheLastWar)"
    )
    HUMAN_MARK_OF_SENTINEL_EBERRONRISINGFROMTHELASTWAR = (
        "Mark of Sentinel (EberronRisingfromtheLastWar)"
    )
    HUMAN_KELDON_PLANESHIFTDOMINARIA = "Keldon (PlaneShiftDominaria)"
    HUMAN_GAVONY_PLANESHIFTINNISTRAD = "Gavony (PlaneShiftInnistrad)"
    HUMAN_KESSIG_PLANESHIFTINNISTRAD = "Kessig (PlaneShiftInnistrad)"
    HUMAN_NEPHALIA_PLANESHIFTINNISTRAD = "Nephalia (PlaneShiftInnistrad)"
    HUMAN_STENSIA_PLANESHIFTINNISTRAD = "Stensia (PlaneShiftInnistrad)"
    HUMAN_STANDARD_HUMAN_PLAYERSHANDBOOK = "Standard Human (PlayersHandbook)"
    HUMAN_VARIANT_HUMAN_PLAYERSHANDBOOK = "Variant Human (PlayersHandbook)"
    KENKU_KENKU_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Kenku (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    KOBOLD_KOBOLD_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Kobold (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    KOBOLD_KOBOLD_UNEARTHEDARCANA = "Kobold (UnearthedArcana)"
    KOBOLD_KOBOLD_VOLOSGUIDETOMONSTERS = "Kobold (VolosGuidetoMonsters)"
    LEONIN_LEONIN_LEONINFEATURES = "Leonin (LeoninFeatures)"
    LIZARDFOLK_LIZARDFOLK_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Lizardfolk (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    LIZARDFOLK_LIZARDFOLK_VOLOSGUIDETOMONSTERS = (
        "Lizardfolk (VolosGuidetoMonsters)"
    )
    MINOTAUR_MINOTAUR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Minotaur (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    ORC_ORC_EBERRONRISINGFROMTHELASTWAR = "Orc (EberronRisingfromtheLastWar)"
    ORC_ORC_EXPLORERSGUIDETOWILDEMOUNT = "Orc (ExplorersGuidetoWildemount)"
    ORC_ORC_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Orc (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    ORC_ORC_PLANESHIFTIXALAN = "Orc (PlaneShiftIxalan)"
    ORC_ORC_VOLOSGUIDETOMONSTERS = "Orc (VolosGuidetoMonsters)"
    SATYR_SATYR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Satyr (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    SATYR_SATYR_MYTHICODYSSEYSOFTHEROS = "Satyr (MythicOdysseysofTheros)"
    SHIFTER_BEASTHIDE_EBERRONRISINGFROMTHELASTWAR = (
        "Beasthide (EberronRisingfromtheLastWar)"
    )
    SHIFTER_LONGTOOTH_EBERRONRISINGFROMTHELASTWAR = (
        "Longtooth (EberronRisingfromtheLastWar)"
    )
    SHIFTER_SWIFTSTRIDE_EBERRONRISINGFROMTHELASTWAR = (
        "Swiftstride (EberronRisingfromtheLastWar)"
    )
    SHIFTER_WILDHUNT_EBERRONRISINGFROMTHELASTWAR = (
        "Wildhunt (EberronRisingfromtheLastWar)"
    )
    SHIFTER_BEASTHIDE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Beasthide (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    SHIFTER_LONGTOOTH_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Longtooth (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    SHIFTER_SWIFTSTRIDE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Swiftstride (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    SHIFTER_WILDHUNT_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Wildhunt (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    SHIFTER_CLIFFWALK_UNEARTHEDARCANA = "Cliffwalk (UnearthedArcana)"
    SHIFTER_RAZORCLAW_UNEARTHEDARCANA = "Razorclaw (UnearthedArcana)"
    TABAXI_TABAXI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Tabaxi (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    TABAXI_TABAXI_VOLOSGUIDETOMONSTERS = "Tabaxi (VolosGuidetoMonsters)"
    TIEFLING_BLOODLINE_OF_BAALZEBUL_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Baalzebul (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_DISPATER_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Dispater (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_FIERNA_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Fierna (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_GLASYA_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Glasya (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_LEVISTUS_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Levistus (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_MAMMON_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Mammon (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_MEPHISTOPHELES_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Mephistopheles (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_ZARIEL_MORDENKAINENSTOMEOFFOES = (
        "Bloodline of Zariel (MordenkainensTomeofFoes)"
    )
    TIEFLING_BLOODLINE_OF_ASMODEUS_PLAYERSHANDBOOK = (
        "Bloodline of Asmodeus (PlayersHandbook)"
    )
    TIEFLING_DEVILS_TONGUE_SWORDCOASTADVENTURERSGUIDE = (
        "Devil's Tongue(SwordCoastAdventurersGuide)"
    )
    TIEFLING_FERAL_SWORDCOASTADVENTURERSGUIDE = (
        "Feral (SwordCoastAdventurersGuide)"
    )
    TIEFLING_HELLFIRE_SWORDCOASTADVENTURERSGUIDE = (
        "Hellfire (SwordCoastAdventurersGuide)"
    )
    TIEFLING_WINGED_SWORDCOASTADVENTURERSGUIDE = (
        "Winged (SwordCoastAdventurersGuide)"
    )
    TIEFLING_ABYSSAL_TIEFLING_UNEARTHEDARCANA = (
        "Abyssal Tiefling (UnearthedArcana)"
    )
    TORTLE_TORTLE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE = (
        "Tortle (MordenkainenPresentsMonstersoftheMultiverse)"
    )
    VERDAN_VERDAN_PLAYERSHANDBOOK = "Verdan (PlayersHandbook)"
    WARFORGED_WARFORGED_EBERRONRISINGFROMTHELASTWAR = (
        "Warforged (EberronRisingfromtheLastWar)"
    )
    WARFORGED_ENVOY_UNEARTHEDARCANA = "Envoy (UnearthedArcana)"
    WARFORGED_JUGGERNAUT_UNEARTHEDARCANA = "Juggernaut (UnearthedArcana)"
    WARFORGED_SKIRMISHER_UNEARTHEDARCANA = "Skirmisher (UnearthedArcana)"


RACE_TO_SUBRACES: frozendict[Race, tuple[Subrace, ...]] = frozendict(
    {
        Race.HUMAN: (
            Subrace.HUMAN_MARK_OF_FINDING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HUMAN_MARK_OF_HANDLING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HUMAN_MARK_OF_MAKING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HUMAN_MARK_OF_PASSAGE_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HUMAN_MARK_OF_SENTINEL_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HUMAN_KELDON_PLANESHIFTDOMINARIA,
            Subrace.HUMAN_GAVONY_PLANESHIFTINNISTRAD,
            Subrace.HUMAN_KESSIG_PLANESHIFTINNISTRAD,
            Subrace.HUMAN_NEPHALIA_PLANESHIFTINNISTRAD,
            Subrace.HUMAN_STENSIA_PLANESHIFTINNISTRAD,
            Subrace.HUMAN_STANDARD_HUMAN_PLAYERSHANDBOOK,
            Subrace.HUMAN_VARIANT_HUMAN_PLAYERSHANDBOOK,
        ),
        Race.ELF: (
            Subrace.ELF_MARK_OF_SHADOW_EBERRONRISINGFROMTHELASTWAR,
            Subrace.ELF_PALLID_ELF_EXPLORERSGUIDETOWILDEMOUNT,
            Subrace.ELF_BISHTAHAR_ELF_PLANESHIFTKALADESH,
            Subrace.ELF_TIRAHAR_ELF_PLANESHIFTKALADESH,
            Subrace.ELF_VAHADAR_ELF_PLANESHIFTKALADESH,
            Subrace.ELF_JURAGA_PLANESHIFTZENDIKAR,
            Subrace.ELF_MUL_DAYA_PLANESHIFTZENDIKAR,
            Subrace.ELF_TAJURU_PLANESHIFTZENDIKAR,
            Subrace.ELF_DARK_ELF_PLAYERSHANDBOOK,
            Subrace.ELF_HIGH_ELF_PLAYERSHANDBOOK,
            Subrace.ELF_WOOD_ELF_PLAYERSHANDBOOK,
            Subrace.ELF_ASTRAL_ELF_SPELLJAMMERADVENTURESINSPACE,
        ),
        Race.DWARF: (
            Subrace.DWARF_HILL_DWARF_PLAYERSHANDBOOK,
            Subrace.DWARF_MOUNTAIN_DWARF_PLAYERSHANDBOOK,
        ),
        Race.HALFLING: (
            Subrace.HALFLING_MARK_OF_HEALING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HALFLING_MARK_OF_HOSPITALITY_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HALFLING_LOTUSDEN_HALFLING_EXPLORERSGUIDETOWILDEMOUNT,
            Subrace.HALFLING_LIGHTFOOT_PLAYERSHANDBOOK,
            Subrace.HALFLING_STOUT_PLAYERSHANDBOOK,
            Subrace.HALFLING_GHOSTWISE_SWORDCOASTADVENTURERSGUIDE,
        ),
        Race.HALF_ELF: (
            Subrace.HALF_ELF_AQUATIC_ELF_HERITAGE_PLAYERSHANDBOOK,
            Subrace.HALF_ELF_DARK_ELF_HERITAGE_PLAYERSHANDBOOK,
            Subrace.HALF_ELF_HIGH_ELF_HERITAGE_PLAYERSHANDBOOK,
            Subrace.HALF_ELF_WOOD_ELF_HERITAGE_PLAYERSHANDBOOK,
        ),
        Race.HALF_ORC: (
            Subrace.HALF_ORC_MARK_OF_FINDING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.HALF_ORC_HALF_ORC_PLAYERSHANDBOOK,
        ),
        Race.TIEFLING: (
            Subrace.TIEFLING_BLOODLINE_OF_BAALZEBUL_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_DISPATER_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_FIERNA_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_GLASYA_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_LEVISTUS_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_MAMMON_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_MEPHISTOPHELES_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_ZARIEL_MORDENKAINENSTOMEOFFOES,
            Subrace.TIEFLING_BLOODLINE_OF_ASMODEUS_PLAYERSHANDBOOK,
            Subrace.TIEFLING_DEVILS_TONGUE_SWORDCOASTADVENTURERSGUIDE,
            Subrace.TIEFLING_FERAL_SWORDCOASTADVENTURERSGUIDE,
            Subrace.TIEFLING_HELLFIRE_SWORDCOASTADVENTURERSGUIDE,
            Subrace.TIEFLING_WINGED_SWORDCOASTADVENTURERSGUIDE,
            Subrace.TIEFLING_ABYSSAL_TIEFLING_UNEARTHEDARCANA,
        ),
        Race.DRAGONBORN: (
            Subrace.DRAGONBORN_DRACONBLOOD_EXPLORERSGUIDETOWILDEMOUNT,
            Subrace.DRAGONBORN_RAVENITE_EXPLORERSGUIDETOWILDEMOUNT,
            Subrace.DRAGONBORN_CHROMATIC_FIZBANSTREASURYOFDRAGONS,
            Subrace.DRAGONBORN_GEM_FIZBANSTREASURYOFDRAGONS,
            Subrace.DRAGONBORN_METALLIC_FIZBANSTREASURYOFDRAGONS,
            Subrace.DRAGONBORN_DRAGONBORN_PLAYERSHANDBOOK,
            Subrace.DRAGONBORN_CHROMATIC_UNEARTHEDARCANA,
            Subrace.DRAGONBORN_GEM_UNEARTHEDARCANA,
            Subrace.DRAGONBORN_METALLIC_UNEARTHEDARCANA,
        ),
        Race.GNOME: (
            Subrace.GNOME_MARK_OF_SCRIBING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.GNOME_FOREST_GNOME_PLAYERSHANDBOOK,
            Subrace.GNOME_ROCK_GNOME_PLAYERSHANDBOOK,
        ),
        Race.AASIMAR: (
            Subrace.AASIMAR_FALLEN_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.AASIMAR_PROTECTOR_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.AASIMAR_SCOURGE_AASIMAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.AASIMAR_FALLEN_AASIMAR_VOLOSGUIDETOMONSTERS,
            Subrace.AASIMAR_PROTECTOR_AASIMAR_VOLOSGUIDETOMONSTERS,
            Subrace.AASIMAR_SCOURGE_AASIMAR_VOLOSGUIDETOMONSTERS,
        ),
        Race.GENASI_AIR: (
            Subrace.GENASI_AIR_AIR_GENASI_ELEMENTALEVILPLAYERSCOMPANION,
            Subrace.GENASI_AIR_AIR_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.GENASI_WATER: (
            Subrace.GENASI_WATER_WATER_GENASI_ELEMENTALEVILPLAYERSCOMPANION,
            Subrace.GENASI_WATER_WATER_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.GENASI_FIRE: (
            Subrace.GENASI_FIRE_FIRE_GENASI_ELEMENTALEVILPLAYERSCOMPANION,
            Subrace.GENASI_FIRE_FIRE_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.GENASI_EARTH: (
            Subrace.GENASI_EARTH_EARTH_GENASI_ELEMENTALEVILPLAYERSCOMPANION,
            Subrace.GENASI_EARTH_EARTH_GENASI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.GOLIATH: (
            Subrace.GOLIATH_GOLIATH_ELEMENTALEVILPLAYERSGUIDE,
            Subrace.GOLIATH_GOLIATH_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.FIRBOLG: (
            Subrace.FIRBOLG_FIRBOLG_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.FIRBOLG_FIRBOLG_VOLOSGUIDETOMONSTERS,
        ),
        Race.TABAXI: (
            Subrace.TABAXI_TABAXI_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.TABAXI_TABAXI_VOLOSGUIDETOMONSTERS,
        ),
        Race.LIZARDFOLK: (
            Subrace.LIZARDFOLK_LIZARDFOLK_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.LIZARDFOLK_LIZARDFOLK_VOLOSGUIDETOMONSTERS,
        ),
        Race.KENKU: (
            Subrace.KENKU_KENKU_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.TORTLE: (
            Subrace.TORTLE_TORTLE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.AARAKOCRA: (
            Subrace.AARAKOCRA_AARAKOCRA_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.BUGBEAR: (
            Subrace.BUGBEAR_BUGBEAR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.BUGBEAR_BUGBEAR_VOLOSGUIDETOMONSTERS,
        ),
        Race.GOBLIN: (
            Subrace.GOBLIN_DANKWOOD_GOBLIN_ADVENTURESWITHMUKDANKWOOD,
            Subrace.GOBLIN_GOBLIN_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.GOBLIN_GOBLIN_PLANESHIFTIXALAN,
            Subrace.GOBLIN_GOBLIN_VOLOSGUIDETOMONSTERS,
        ),
        Race.HOBGOBLIN: (
            Subrace.HOBGOBLIN_HOBGOBLIN_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.HOBGOBLIN_HOBGOBLIN_UNEARTHEDARCANA,
            Subrace.HOBGOBLIN_HOBGOBLIN_VOLOSGUIDETOMONSTERS,
        ),
        Race.KOBOLD: (
            Subrace.KOBOLD_KOBOLD_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.KOBOLD_KOBOLD_UNEARTHEDARCANA,
            Subrace.KOBOLD_KOBOLD_VOLOSGUIDETOMONSTERS,
        ),
        Race.ORC: (
            Subrace.ORC_ORC_EBERRONRISINGFROMTHELASTWAR,
            Subrace.ORC_ORC_EXPLORERSGUIDETOWILDEMOUNT,
            Subrace.ORC_ORC_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.ORC_ORC_PLANESHIFTIXALAN,
            Subrace.ORC_ORC_VOLOSGUIDETOMONSTERS,
        ),
        Race.WARFORGED: (
            Subrace.WARFORGED_WARFORGED_EBERRONRISINGFROMTHELASTWAR,
            Subrace.WARFORGED_ENVOY_UNEARTHEDARCANA,
            Subrace.WARFORGED_JUGGERNAUT_UNEARTHEDARCANA,
            Subrace.WARFORGED_SKIRMISHER_UNEARTHEDARCANA,
        ),
        Race.CHANGELING: (
            Subrace.CHANGELING_CHANGELING_EBERRONRISINGFROMTHELASTWAR,
            Subrace.CHANGELING_CHANGELING_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.CHANGELING_CHANGELING_UNEARTHEDARCANA,
        ),
        Race.SHIFTER: (
            Subrace.SHIFTER_BEASTHIDE_EBERRONRISINGFROMTHELASTWAR,
            Subrace.SHIFTER_LONGTOOTH_EBERRONRISINGFROMTHELASTWAR,
            Subrace.SHIFTER_SWIFTSTRIDE_EBERRONRISINGFROMTHELASTWAR,
            Subrace.SHIFTER_WILDHUNT_EBERRONRISINGFROMTHELASTWAR,
            Subrace.SHIFTER_BEASTHIDE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.SHIFTER_LONGTOOTH_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.SHIFTER_SWIFTSTRIDE_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.SHIFTER_WILDHUNT_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.SHIFTER_CLIFFWALK_UNEARTHEDARCANA,
            Subrace.SHIFTER_RAZORCLAW_UNEARTHEDARCANA,
        ),
        Race.MINOTAUR: (
            Subrace.MINOTAUR_MINOTAUR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
        ),
        Race.CENTAUR: (
            Subrace.CENTAUR_GRUUL_CENTAUR_GUILDMASTERSGUIDETORAVNICA,
            Subrace.CENTAUR_SELESNYA_CENTAUR_GUILDMASTERSGUIDETORAVNICA,
            Subrace.CENTAUR_CENTAURS_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.CENTAUR_LAGONNA_MYTHICODYSSEYSOFTHEROS,
            Subrace.CENTAUR_PHERES_MYTHICODYSSEYSOFTHEROS,
        ),
        Race.SATYR: (
            Subrace.SATYR_SATYR_MORDENKAINENPRESENTSMONSTERSOFTHEMULTIVERSE,
            Subrace.SATYR_SATYR_MYTHICODYSSEYSOFTHEROS,
        ),
        Race.LEONIN: (Subrace.LEONIN_LEONIN_LEONINFEATURES,),
        Race.VERDAN: (Subrace.VERDAN_VERDAN_PLAYERSHANDBOOK,),
        Race.GRUNG: (Subrace.GRUNG_GRUNG_PLAYERSHANDBOOK,),
    }
)
