from __future__ import annotations

from datetime import datetime
from typing import Any

from dnd_character_creator.character.blueprint.blueprint import Blueprint
from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field


class Increment(BaseModel):
    """A single increment in the build process.

    Captures the state after applying a BuildingBlock, including
    both the resulting blueprint state and the diff that was generated.
    """

    model_config = ConfigDict(frozen=True, arbitrary_types_allowed=True)

    index: int = Field(
        description="Sequential index of this increment in the build process"
    )
    blueprint_state: Blueprint = Field(
        description="Complete blueprint state AFTER applying the building block"
    )
    diff: Blueprint = Field(
        description="The diff (changes) generated by the building block"
    )
    timestamp: datetime = Field(
        default_factory=datetime.now,
        description="When this increment was created",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Optional user-provided metadata for this increment",
    )

    def verify_consistency(self) -> bool:
        """Verify that the diff fields match what's set in the blueprint state.

        Returns:
            True if increment data is internally consistent
        """
        for field_name in self.diff.model_fields_set:
            if field_name not in self.blueprint_state.model_fields_set:
                return False
        return True
