from enum import StrEnum, auto


class Condition(StrEnum):
    BLINDED = auto()
    CHARMED = auto()
    DEAFENED = auto()
    EXHAUSTION_1 = auto()
    EXHAUSTION_2 = auto()
    EXHAUSTION_3 = auto()
    EXHAUSTION_4 = auto()
    EXHAUSTION_5 = auto()
    EXHAUSTION_6 = auto()
    FRIGHTENED = auto()
    GRAPPLED = auto()
    INCAPACITATED = auto()
    INVISIBLE = auto()
    PARALYZED = auto()
    PETRIFIED = auto()
    POISONED = auto()
    PRONE = auto()
    RESTRAINED = auto()
    STUNNED = auto()
    UNCONSCIOUS = auto()
    CONCENTRATION = auto()
