from __future__ import annotations

from enum import Enum


class Background(str, Enum):
    ACOLYTE = "Acolyte"
    ANTHROPOLOGIST = "Anthropologist"
    ARCHAEOLOGIST = "Archaeologist"
    ATHLETE = "Athlete"
    CHARLATAN = "Charlatan"
    CITY_WATCH = "City Watch"
    CLAN_CRAFTER = "Clan Crafter"
    CLOISTERED_SCHOLAR = "Cloistered Scholar"
    COURTIER = "Courtier"
    CRIMINAL = "Criminal"
    ENTERTAINER = "Entertainer"
    FACELESS = "Faceless"
    FACTION_AGENT = "Faction Agent"
    FAR_TRAVELER = "Far Traveler"
    FEYLOST = "Feylost"
    FISHER = "Fisher"
    FOLK_HERO = "Folk Hero"
    GIANT_FOUNDLING = "Giant Foundling"
    GLADIATOR = "Gladiator"
    GUILD_ARTISAN = "Guild Artisan"
    GUILD_MERCHANT = "Guild Merchant"
    HAUNTED_ONE = "Haunted One"
    HERMIT = "Hermit"
    HOUSE_AGENT = "House Agent"
    INHERITOR = "Inheritor"
    INVESTIGATOR_SCAG = "Investigator"
    KNIGHT = "Knight"
    KNIGHT_OF_THE_ORDER = "Knight of the Order"
    MARINE = "Marine"
    MERCENARY_VETERAN = "Mercenary Veteran"
    NOBLE = "Noble"
    OUTLANDER = "Outlander"
    PIRATE = "Pirate"
    REWARDED = "Rewarded"
    RUINED = "Ruined"
    RUNE_CARVER = "Rune Carver"
    SAGE = "Sage"
    SAILOR = "Sailor"
    SHIPWRIGHT = "Shipwright"
    SMUGGLER = "Smuggler"
    SOLDIER = "Soldier"
    SPY = "Spy"
    URBAN_BOUNTY_HUNTER = "Urban Bounty Hunter"
    URCHIN = "Urchin"
    UTHGARDT_TRIBE_MEMBER = "Uthgardt Tribe Member"
    WATERDHAVIAN_NOBLE = "Waterdhavian Noble"
    WITCHLIGHT_HAND = "Witchlight Hand"
