#!/usr/bin/env python3
"""
Validate that the frontend block filtering matches the Python type system.

Two comparison systems:
  1. JSON-based (frontend port): uses blocks-generated.json + TypeScript argCompatible logic
  2. Python-native: uses actual Python type hints with full TypeVar resolution,
     deserialized back to Python objects and checked with _arg_compatible

Reports differences per test state and gives a final pass/fail verdict.

Usage:
  python3 frontend/scripts/validate_filtering.py
  python3 frontend/scripts/validate_filtering.py --depth 3   # default
  python3 frontend/scripts/validate_filtering.py --depth 2   # faster
"""

from __future__ import annotations

import argparse
import json
import sys
import typing
from pathlib import Path
from typing import TypedDict
from typing import get_args

ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT))

import annotated_types  # noqa: E402

from dnd.character.blueprint.building_blocks import AnyBuildingBlock  # noqa: E402
from dnd.character.blueprint.building_blocks.building_block import BuildingBlock  # noqa: E402
from dnd.character.blueprint.sentinels import (  # noqa: E402
    AnyClassLevel,
    AnySorcererLevel,
    AnyStatChoices,
    AnyWizardLevel,
    ClassPreSubclassLevel,
    FirstSubclassPreLevel,
    MaybeCharacterData,
    MaybeHealth,
    MaybeRace,
    MaybeStats,
    SecondSubclassPreLevel,
    SorcererPreSubclassLevel,
    SorcererSubclassLevel,
    ThirdSubclassPreLevel,
    WizardPreSubclassLevel,
    WizardSubclassLevel,
)
from dnd.character.blueprint.states.state import Blueprint  # noqa: E402
from dnd.character.blueprint.character_data import CharacterData  # noqa: E402
from dnd.character.blueprint.states.basic_presentable import PresentableBasicBlueprint  # noqa: E402
from dnd.character.blueprint.states.sorcerer.base import SorcererBlueprint  # noqa: E402
from dnd.character.blueprint.states.wizard.base import WizardBlueprint  # noqa: E402
from dnd.character.blueprint.states.wizard.level18 import WizardLevel18Blueprint  # noqa: E402
from dnd.character.blueprint.states.wizard.level20 import WizardLevel20Blueprint  # noqa: E402
from dnd.character.race.race import Race  # noqa: E402
from dnd.character.stats import Stats  # noqa: E402
from frontend.scripts.generate_blocks import (  # noqa: E402
    _collect_typevar_bindings,
    _sig_from_hint,
)


class _ArgSpec(TypedDict, total=False):
    kind: str
    name: str
    values: list[object]
    origin: str
    args: list[_ArgSpec]
    members: list[object]


class _BlueprintSig(TypedDict):
    origin: str
    args: list[_ArgSpec]


class _BlockSig(TypedDict, total=False):
    input: _BlueprintSig
    output: _BlueprintSig


class _State(TypedDict):
    origin: str
    args: list[_ArgSpec]


class _BlockInfo(TypedDict, total=False):
    class_name: str
    blueprint_sig: _BlockSig


class _Failure(TypedDict):
    context: str
    state: str
    only_frontend: list[str]
    only_python: list[str]


class _MetaJson(TypedDict):
    emptyBlueprintArgs: list[_ArgSpec]
    originHierarchy: dict[str, list[str]]


# ---------------------------------------------------------------------------
# Load JSON data (generated by generate_blocks.py)
# ---------------------------------------------------------------------------

_BLOCKS_JSON = ROOT / "frontend" / "src" / "data" / "blocks-generated.json"
_META_JSON = ROOT / "frontend" / "src" / "data" / "pipeline-meta.json"

blocks_data: list[_BlockInfo] = json.loads(_BLOCKS_JSON.read_text())
meta: _MetaJson = json.loads(_META_JSON.read_text())

empty_blueprint_args: list[_ArgSpec] = meta["emptyBlueprintArgs"]
origin_hierarchy: dict[str, list[str]] = meta["originHierarchy"]

block_by_class: dict[str, _BlockInfo] = {str(b["class_name"]): b for b in blocks_data}

# Get all concrete block classes from the AnyBuildingBlock union
_union_args = get_args(AnyBuildingBlock)
_all_block_classes: list[type] = list(get_args(_union_args[0]))
class_map: dict[str, type] = {cls.__name__: cls for cls in _all_block_classes}

# ---------------------------------------------------------------------------
# Deserialization registry (JSON spec -> Python type object)
# ---------------------------------------------------------------------------

_TYPE_REGISTRY: dict[str, object] = {
    "Race": Race,
    "Stats": Stats,
    "int": int,
    "CharacterData": CharacterData,
    "AnyClassLevel": AnyClassLevel,
    "AnySorcererLevel": AnySorcererLevel,
    "AnyWizardLevel": AnyWizardLevel,
    "FirstSubclassPreLevel": FirstSubclassPreLevel,
    "SecondSubclassPreLevel": SecondSubclassPreLevel,
    "ThirdSubclassPreLevel": ThirdSubclassPreLevel,
    "MaybeHealth": MaybeHealth,
    "MaybeRace": MaybeRace,
    "MaybeStats": MaybeStats,
    "MaybeCharacterData": MaybeCharacterData,
    "AnyStatChoices": AnyStatChoices,
    "Gt(gt=0)": annotated_types.Gt(gt=0),
}

_GENERIC_REGISTRY: dict[str, object] = {
    "WizardPreSubclassLevel": WizardPreSubclassLevel,
    "WizardSubclassLevel": WizardSubclassLevel,
    "SorcererPreSubclassLevel": SorcererPreSubclassLevel,
    "SorcererSubclassLevel": SorcererSubclassLevel,
    "ClassPreSubclassLevel": ClassPreSubclassLevel,
    "Annotated": typing.Annotated,
}


def deser_arg(spec: _ArgSpec) -> object:
    """Deserialize a JSON ArgSpec back to a Python type object."""
    kind = spec["kind"]
    if kind == "none":
        return type(None)
    if kind == "free":
        return typing.TypeVar("_Free")
    if kind == "literal":
        vals: tuple[object, ...] = tuple(spec["values"])
        return typing.Literal[vals] if len(vals) > 1 else typing.Literal[vals[0]]
    if kind == "type":
        name = spec["name"]
        obj = _TYPE_REGISTRY.get(str(name))
        if obj is not None:
            return obj
        cls = class_map.get(str(name))
        if cls is not None:
            return cls
        return object  # fallback — treat as unknown type
    if kind == "generic":
        origin_name = spec["origin"]
        origin_obj = _GENERIC_REGISTRY.get(str(origin_name))
        if origin_obj is None:
            return object  # fallback
        deser_args: tuple[object, ...] = tuple(deser_arg(a) for a in spec["args"])
        if origin_obj is typing.Annotated:
            return typing.Annotated[deser_args]
        return origin_obj[deser_args]  # type: ignore[index]
    return object  # unknown kind


# ---------------------------------------------------------------------------
# System 1: TypeScript-ported JSON logic (mirrors blueprintState.ts exactly)
# ---------------------------------------------------------------------------


def arg_compatible_json(current: _ArgSpec, expected: _ArgSpec) -> bool:
    if expected["kind"] == "free":
        return True
    if expected["kind"] == "type" and current["kind"] == "literal":
        return True  # literal enum value IS compatible with enum class bound
    if current["kind"] != expected["kind"]:
        return False
    if current["kind"] == "none":
        return True
    if current["kind"] == "type":
        return bool(current["name"] == expected["name"])
    if current["kind"] == "literal":
        expected_set = {str(v) for v in expected["values"]}
        return all(str(v) in expected_set for v in current["values"])
    if current["kind"] == "generic":
        if current["origin"] != expected["origin"]:
            return False
        cur_args = current["args"]
        exp_args = expected["args"]
        return all(
            arg_compatible_json(cur_args[i], e)
            for i, e in enumerate(exp_args)
            if i < len(cur_args)
        )
    return False


def is_sub_origin_json(current: str, expected: str) -> bool:
    return current == expected or expected in origin_hierarchy.get(current, [])


def is_compatible_json(block_info: _BlockInfo, state: _State) -> bool:
    sig = block_info.get("blueprint_sig")
    if not sig or not isinstance(sig, dict) or not sig.get("input"):
        return True
    inp: _BlueprintSig = sig["input"]
    if not is_sub_origin_json(str(state["origin"]), str(inp["origin"])):
        return False
    state_args = state["args"]
    inp_args = inp["args"]
    pair = min(len(state_args), len(inp_args))
    return all(arg_compatible_json(state_args[j], inp_args[j]) for j in range(pair))


def apply_block_json(state: _State, block_info: _BlockInfo) -> _State:
    if not is_compatible_json(block_info, state):
        return state
    sig = block_info.get("blueprint_sig")
    if not sig or not isinstance(sig, dict) or not sig.get("output"):
        return state
    out: _BlueprintSig = sig["output"]
    state_args = state["args"]
    out_args = out["args"]
    new_args: list[_ArgSpec] = [
        state_args[j] if a["kind"] == "free" and j < len(state_args) else a
        for j, a in enumerate(out_args)
    ]
    return {"origin": out["origin"], "args": new_args}


def compatible_set_json(state: _State) -> set[str]:
    return {str(b["class_name"]) for b in blocks_data if is_compatible_json(b, state)}


# ---------------------------------------------------------------------------
# System 2: Python-native (resolved type hints + deserialization + _arg_compatible)
# ---------------------------------------------------------------------------

# Blueprint subclass registry for origin checks
_BLUEPRINT_SUBCLASS_REGISTRY: dict[str, type] = {"Blueprint": Blueprint}
for _cls in _all_block_classes:
    for _c in _cls.__mro__:
        if isinstance(_c, type) and issubclass(_c, Blueprint) and _c is not Blueprint:
            _BLUEPRINT_SUBCLASS_REGISTRY[_c.__name__] = _c
# Add known Blueprint subclasses that don't appear directly in block MROs
for _bp_cls in (
    PresentableBasicBlueprint,
    SorcererBlueprint,
    WizardBlueprint,
    WizardLevel18Blueprint,
    WizardLevel20Blueprint,
):
    _BLUEPRINT_SUBCLASS_REGISTRY[_bp_cls.__name__] = _bp_cls


def _get_block_sig_as_json(cls: type[BuildingBlock]) -> _BlockSig | None:
    """
    Produce the same 19-arg JSON sig as generate_blocks.py for a block class.
    This is the 'Python truth' — fully resolved type annotations.
    """
    apply_fn = next(
        (c.__dict__["apply"] for c in cls.__mro__ if "apply" in c.__dict__), None
    )
    if apply_fn is None:
        return None
    try:
        hints = typing.get_type_hints(apply_fn)
    except Exception:
        return None
    bindings = _collect_typevar_bindings(cls)
    input_sig = _sig_from_hint(hints.get("blueprint"), bindings)
    output_sig = _sig_from_hint(hints.get("return"), bindings)
    if input_sig is None and output_sig is None:
        return None
    result: _BlockSig = {}
    if input_sig is not None:
        result["input"] = input_sig  # type: ignore[typeddict-item]
    if output_sig is not None:
        result["output"] = output_sig  # type: ignore[typeddict-item]
    return result


def arg_compatible_py(current: _ArgSpec, expected: _ArgSpec) -> bool:
    """
    Python-native arg compatibility check mirroring the frontend logic exactly.

    Uses Python issubclass for origin checks but otherwise mirrors arg_compatible_json,
    including the 'literal matches type' fix and recursive generic handling.
    Note: _arg_compatible from _validate_pipeline.py is NOT used here because it
    (a) lacks the literal-matches-type fix and (b) doesn't recurse into inner generic
    args with the fix applied. Differences with _validate_pipeline.py are documented
    as known bugs in that module.
    """
    if expected["kind"] == "free":
        return True
    # literal value IS compatible with a class type bound (e.g. Literal[0] ~ FirstSubclassPreLevel)
    if expected["kind"] == "type" and current["kind"] == "literal":
        return True
    if current["kind"] != expected["kind"]:
        return False
    if current["kind"] == "none":
        return True
    if current["kind"] == "type":
        c_name = str(current["name"])
        e_name = str(expected["name"])
        c_cls = _TYPE_REGISTRY.get(c_name) or class_map.get(c_name)
        e_cls = _TYPE_REGISTRY.get(e_name) or class_map.get(e_name)
        if isinstance(c_cls, type) and isinstance(e_cls, type):
            return issubclass(c_cls, e_cls)
        return bool(current["name"] == expected["name"])
    if current["kind"] == "literal":
        expected_set = {str(v) for v in expected["values"]}
        return all(str(v) in expected_set for v in current["values"])
    if current["kind"] == "generic":
        c_origin = _GENERIC_REGISTRY.get(str(current["origin"]))
        e_origin = _GENERIC_REGISTRY.get(str(expected["origin"]))
        if c_origin is None or e_origin is None:
            if current["origin"] != expected["origin"]:
                return False
        elif c_origin is not e_origin:
            if isinstance(c_origin, type) and isinstance(e_origin, type):
                if not issubclass(c_origin, e_origin):
                    return False
            else:
                return False
        cur_args = current["args"]
        exp_args = expected["args"]
        return all(
            arg_compatible_py(cur_args[i], e)
            for i, e in enumerate(exp_args)
            if i < len(cur_args)
        )
    return False


def is_sub_origin_py(current_name: str, expected_name: str) -> bool:
    current_cls = _BLUEPRINT_SUBCLASS_REGISTRY.get(current_name)
    expected_cls = _BLUEPRINT_SUBCLASS_REGISTRY.get(expected_name)
    if current_cls is None or expected_cls is None:
        return current_name == expected_name
    return issubclass(current_cls, expected_cls)


# Cache block sigs to avoid repeated computation
_sig_cache: dict[str, _BlockSig | None] = {}


def _cached_sig(cls_name: str) -> _BlockSig | None:
    if cls_name not in _sig_cache:
        cls = class_map.get(cls_name)
        _sig_cache[cls_name] = _get_block_sig_as_json(cls) if cls else None
    return _sig_cache[cls_name]


def is_compatible_py(cls_name: str, state: _State) -> bool:
    sig = _cached_sig(cls_name)
    if not sig or not sig.get("input"):
        return True
    inp: _BlueprintSig = sig["input"]
    if not is_sub_origin_py(str(state["origin"]), str(inp["origin"])):
        return False
    state_args = state["args"]
    inp_args = inp["args"]
    pair = min(len(state_args), len(inp_args))
    return all(arg_compatible_py(state_args[j], inp_args[j]) for j in range(pair))


def apply_block_py_state(state: _State, cls_name: str) -> _State:
    if not is_compatible_py(cls_name, state):
        return state
    sig = _cached_sig(cls_name)
    if not sig or not sig.get("output"):
        return state
    out: _BlueprintSig = sig["output"]
    state_args2 = state["args"]
    out_args = out["args"]
    new_args: list[_ArgSpec] = [
        state_args2[j] if a["kind"] == "free" and j < len(state_args2) else a
        for j, a in enumerate(out_args)
    ]
    return {"origin": out["origin"], "args": new_args}


def compatible_set_py(state: _State) -> set[str]:
    return {cls_name for cls_name in class_map if is_compatible_py(cls_name, state)}


# ---------------------------------------------------------------------------
# Cross-validation helpers
# ---------------------------------------------------------------------------


def _fmt_spec(spec: _ArgSpec) -> str:
    """Compact representation of a JSON arg spec for diff output."""
    k = spec.get("kind", "?")
    if k == "none":
        return "None"
    if k == "free":
        return "_"
    if k == "literal":
        return f"Literal{spec['values']}"
    if k == "type":
        return str(spec["name"])
    if k == "generic":
        args_list = spec.get("args", [])
        inner = ", ".join(_fmt_spec(a) for a in args_list)
        return f"{spec['origin']}[{inner}]"
    return str(spec)


def _fmt_state(state: _State) -> str:
    args_str = ", ".join(_fmt_spec(a) for a in state["args"])
    return f"{state['origin']}[{args_str}]"


def compare_at_state(
    state: _State,
    context: str,
    failures: list[_Failure],
    verbose: bool = False,
) -> bool:
    ts_compat = compatible_set_json(state)
    py_compat = compatible_set_py(state)

    only_json = ts_compat - py_compat
    only_py = py_compat - ts_compat

    if only_json or only_py:
        failures.append(
            {
                "context": context,
                "state": _fmt_state(state),
                "only_frontend": sorted(only_json),
                "only_python": sorted(only_py),
            }
        )
        return False
    if verbose:
        sys.stdout.write(f"  OK [{len(ts_compat)} blocks]: {context}\n")
    return True


# ---------------------------------------------------------------------------
# Test suite
# ---------------------------------------------------------------------------


def run_validation(max_depth: int = 3, verbose: bool = False) -> int:
    sys.stdout.write(
        f"Running frontend filtering validation (max_depth={max_depth})...\n"
    )
    failures: list[_Failure] = []
    total = 0

    empty_state: _State = {"origin": "Blueprint", "args": empty_blueprint_args}

    # Warm up the sig cache for all blocks up front
    for cls_name in class_map:
        _cached_sig(cls_name)

    def recurse(state: _State, path: list[str], depth: int) -> None:
        nonlocal total
        total += 1
        context = " -> ".join(path) if path else "initial"
        compare_at_state(state, context, failures, verbose=verbose)

        if depth >= max_depth:
            return

        # Only recurse into blocks compatible with both systems (intersection)
        ts_compat = compatible_set_json(state)
        py_compat = compatible_set_py(state)
        reachable = sorted(ts_compat | py_compat)  # include both for full coverage

        for cls_name in reachable:
            b_info = block_by_class.get(cls_name)
            if b_info is None:
                continue

            # Compute next state with each system separately — they should agree
            next_json = apply_block_json(state, b_info)
            next_py = apply_block_py_state(state, cls_name)

            # If the states differ, track both to expose downstream differences
            if next_json != next_py:
                # Detect state divergence — report as a separate issue
                total += 1
                sig_j = json.dumps(next_json.get("args", []), sort_keys=True)
                sig_p = json.dumps(next_py.get("args", []), sort_keys=True)
                if sig_j != sig_p:
                    failures.append(
                        {
                            "context": f"STATE DIVERGE after {context} -> {cls_name}",
                            "state": f"json={_fmt_state(next_json)}\n       py={_fmt_state(next_py)}",
                            "only_frontend": [],
                            "only_python": [],
                        }
                    )

            # Recurse using the json-based next state (canonical path)
            recurse(next_json, path + [cls_name], depth + 1)

    recurse(empty_state, [], 0)

    # ------------------------------------------------------------------
    # Print results
    # ------------------------------------------------------------------
    sep = "=" * 72

    sys.stdout.write(f"\n{sep}\n")
    sys.stdout.write(f"States tested : {total}\n")
    sys.stdout.write(f"Failures      : {len(failures)}\n")
    sys.stdout.write(f"{sep}\n")

    if not failures:
        sys.stdout.write(
            "RESULT: PASS — frontend filtering exactly matches Python type system\n"
        )
        return 0

    sys.stdout.write("RESULT: FAIL — differences found:\n\n")
    for i, f in enumerate(failures, 1):
        sys.stdout.write(f"  [{i}] {f['context']}\n")
        sys.stdout.write(f"       state  = {f['state']}\n")
        if f["only_frontend"]:
            sys.stdout.write(
                f"       frontend-only (may be over-permissive): {f['only_frontend']}\n"
            )
        if f["only_python"]:
            sys.stdout.write(
                f"       python-only   (may be over-permissive): {f['only_python']}\n"
            )
        sys.stdout.write("\n")

    return 1


# ---------------------------------------------------------------------------
# Additional unit-level tests for arg_compatible functions
# ---------------------------------------------------------------------------


def run_unit_tests() -> int:
    sys.stdout.write("\nRunning arg_compatible unit tests...\n")
    errors: list[str] = []

    def check(label: str, got: bool, expected: bool) -> None:
        if got != expected:
            errors.append(f"  FAIL {label}: got {got}, expected {expected}")
        else:
            sys.stdout.write(f"  ok   {label}\n")

    free_spec: _ArgSpec = {"kind": "free"}
    none_spec: _ArgSpec = {"kind": "none"}
    lit0: _ArgSpec = {"kind": "literal", "values": [0]}
    lit1: _ArgSpec = {"kind": "literal", "values": [1]}
    type_race: _ArgSpec = {"kind": "type", "name": "Race"}
    type_first_pre: _ArgSpec = {"kind": "type", "name": "FirstSubclassPreLevel"}

    wiz_pre0: _ArgSpec = {
        "kind": "generic",
        "origin": "WizardPreSubclassLevel",
        "args": [lit0, none_spec],
    }
    wiz_pre1: _ArgSpec = {
        "kind": "generic",
        "origin": "WizardPreSubclassLevel",
        "args": [lit1, none_spec],
    }
    sorc_pre0: _ArgSpec = {
        "kind": "generic",
        "origin": "SorcererPreSubclassLevel",
        "args": [lit0, none_spec],
    }

    # -- free always matches --
    check(
        "free expected, any current -> True (json)",
        arg_compatible_json(lit0, free_spec),
        True,
    )
    check(
        "free expected, any current -> True (py)",
        arg_compatible_py(lit0, free_spec),
        True,
    )

    # -- none matches none --
    check(
        "none vs none -> True (json)", arg_compatible_json(none_spec, none_spec), True
    )
    check("none vs none -> True (py)", arg_compatible_py(none_spec, none_spec), True)

    # -- none does NOT match wizard level generic --
    check(
        "none vs WizPreSubLvl -> False (json)",
        arg_compatible_json(none_spec, wiz_pre0),
        False,
    )
    check(
        "none vs WizPreSubLvl -> False (py)",
        arg_compatible_py(none_spec, wiz_pre0),
        False,
    )

    # -- same generic matches same generic --
    check(
        "wiz_pre0 vs wiz_pre0 -> True (json)",
        arg_compatible_json(wiz_pre0, wiz_pre0),
        True,
    )
    check(
        "wiz_pre0 vs wiz_pre0 -> True (py)", arg_compatible_py(wiz_pre0, wiz_pre0), True
    )

    # -- different level does NOT match --
    check(
        "wiz_pre1 vs wiz_pre0 -> False (json)",
        arg_compatible_json(wiz_pre1, wiz_pre0),
        False,
    )
    check(
        "wiz_pre1 vs wiz_pre0 -> False (py)",
        arg_compatible_py(wiz_pre1, wiz_pre0),
        False,
    )

    # -- literal matches type (THE KEY FIX for sorcerer) --
    check(
        "lit0 vs FirstSubclassPre -> True (json)",
        arg_compatible_json(lit0, type_first_pre),
        True,
    )
    check(
        "lit0 vs FirstSubclassPre -> True (py)",
        arg_compatible_py(lit0, type_first_pre),
        True,
    )

    # -- literal matches any type bound (by design: enum values match their class bound) --
    # Note: the fix is intentionally broad — we accept Literal[n] vs any type class
    # in practice this only fires at positions where enum literals live (level slots)
    check("lit0 vs Race -> True (json)", arg_compatible_json(lit0, type_race), True)
    check("lit0 vs Race -> True (py)", arg_compatible_py(lit0, type_race), True)

    # -- wrong class generic is False --
    check(
        "sorc_pre0 vs wiz_pre0 -> False (json)",
        arg_compatible_json(sorc_pre0, wiz_pre0),
        False,
    )
    check(
        "sorc_pre0 vs wiz_pre0 -> False (py)",
        arg_compatible_py(sorc_pre0, wiz_pre0),
        False,
    )

    # -- free inner matches concrete inner --
    wiz_sub_free_subclass: _ArgSpec = {
        "kind": "generic",
        "origin": "WizardSubclassLevel",
        "args": [lit1, free_spec],
    }
    wiz_sub_concrete: _ArgSpec = {
        "kind": "generic",
        "origin": "WizardSubclassLevel",
        "args": [lit1, _ArgSpec(kind="type", name="AnyWizardLevel")],
    }
    check(
        "WizardSubLvl[1,free] vs WizardSubLvl[1,concrete] -> True (json)",
        arg_compatible_json(wiz_sub_concrete, wiz_sub_free_subclass),
        True,
    )
    check(
        "WizardSubLvl[1,free] vs WizardSubLvl[1,concrete] -> True (py)",
        arg_compatible_py(wiz_sub_concrete, wiz_sub_free_subclass),
        True,
    )

    sys.stdout.write(f"\n  Unit tests: {14 - len(errors)} / 14 passed\n")
    for err in errors:
        sys.stdout.write(f"{err}\n")
    return len(errors)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--depth",
        type=int,
        default=3,
        help="Max chain depth to test (default: 3)",
    )
    parser.add_argument(
        "--verbose", action="store_true", help="Print each state checked"
    )
    args = parser.parse_args()

    unit_failures = run_unit_tests()
    integration_result = run_validation(max_depth=args.depth, verbose=args.verbose)

    total_failures = unit_failures + integration_result
    if total_failures == 0:
        sys.stdout.write("\nAll checks passed.\n")
    else:
        sys.stdout.write(f"\n{total_failures} check(s) failed.\n")
    return 0 if total_failures == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
